# Uncomment the next line to define a global platform for your project
# platform :ios, ’10.0’

target 'TestMessenger' do
  use_frameworks!

	pod 'SDWebImage/WebP'
	pod 'Alamofire', '~> 4.4'

  # Pods for TestMessenger

end
